# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: learning_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13learning_data.proto\"I\n\x0cLearningData\x12\x15\n\x0binstruction\x18\x01 \x01(\t:\x00\x12\x10\n\x06\x64\x65tail\x18\x02 \x01(\t:\x00\x12\x10\n\x06speech\x18\x03 \x01(\t:\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'learning_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LEARNINGDATA']._serialized_start=23
  _globals['_LEARNINGDATA']._serialized_end=96
# @@protoc_insertion_point(module_scope)
