# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: template_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13template_data.proto\x12\rTemplateScene\"C\n\x0cTemplateData\x12\x0e\n\x04text\x18\x01 \x01(\t:\x00\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x14\n\naudio_path\x18\x03 \x01(\t:\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPLATEDATA']._serialized_start=38
  _globals['_TEMPLATEDATA']._serialized_end=105
# @@protoc_insertion_point(module_scope)
