input:
  - name: "camera"
    entrypoint: "camera_widget.CameraWidget.start"
    exitpoint: ""
    next:
      - "processing:yolov8"
  - name: "websocket"
    entrypoint: "websocket_widget.WebsocketWidget.start"
    exitpoint: ""
    next:
      - "service:template"
processing:
  - name: "yolov8"
    entrypoint: "Yolov8.detector.Yolov8Detector.run"
    exitpoint: ""
    next:
      - "service:template"
      - "output:video_output"
service:
  - name: "template"
    entrypoint: "template_service.template_service.TemplateService.run"
    exitpoint: ""
    next:
      - "input:websocket|output_send"
output:
  - name: "video_output"
    entrypoint: "video_output.VideoOutput.play"
    exitpoint: "video_output.VideoOutput.stop"
