input:
  - name: "camera"
    entrypoint: "camera_widget.CameraWidget.start"
    exitpoint: ""
    next:
      - "service:learning"
      - "output:video_output"
  - name: "websocket"
    entrypoint: "websocket_widget.WebsocketWidget.start"
    exitpoint: ""
    next:
      - "service:learning"
service:
  - name: "learning"
    entrypoint: "learning_service.learning_service.LearningService.run"
    exitpoint: ""
    next:
      - "input:websocket|output_send"
output:
  - name: "video_output"
    entrypoint: "video_output.VideoOutput.play"
    exitpoint: "video_output.VideoOutput.stop"
