input:
  - name: "camera"
    entrypoint: "camera_widget.CameraWidget.start"
    exitpoint: ""
    next:
      - "output:video_output"
  - name: "websocket"
    entrypoint: "websocket_widget.WebsocketWidget.start"
    exitpoint: ""
    next:
      - "service:martial_arts"
service:
  - name: "martial_arts"
    entrypoint: "martial_arts_service.martial_arts_service.MartialArtsService.run"
    exitpoint: ""
    next:
      - "input:websocket|output_send"
output:
  - name: "video_output"
    entrypoint: "video_output.VideoOutput.play"
    exitpoint: "video_output.VideoOutput.stop"
