input:
  - name: "camera"
    entrypoint: "camera_widget.CameraWidget.start"
    exitpoint: ""
    next:
      - "service:memory_assistance"
      - "output:video_output"
  - name: "audio"
    entrypoint: "audio_widget.AudioWidget.start"
    exitpoint: ""
    next:
      - "processing:whisper"
  - name: "websocket"
    entrypoint: "websocket_widget.WebsocketWidget.start"
    exitpoint: ""
    next:
      - "service:memory_assistance"
  - name: "keyboard"
    entrypoint: "keyboard_widget.KeyboardWidget.start"
    exitpoint: ""
    next:
      - "service:memory_assistance"
processing:
  - name: "whisper"
    entrypoint: "Whisper.transcribe.Transcriber.to_text"
    exitpoint: ""
    next:
      - "service:memory_assistance"
service:
  - name: "memory_assistance"
    entrypoint: "memory_assistance_service.memory_assistance_service.MemoryAssistanceService.run"
    exitpoint: ""
    next:
      - "input:websocket|output_send"
output:
  - name: "video_output"
    entrypoint: "video_output.VideoOutput.play"
    exitpoint: "video_output.VideoOutput.stop"
