input:
  - name: "camera"
    entrypoint: "camera_widget.CameraWidget.start"
    exitpoint: ""
    next:
      - "service:pandalens"
      - "output:video_output"
  - name: "websocket"
    entrypoint: "websocket_widget.WebsocketWidget.start"
    exitpoint: ""
    next:
      - "service:pandalens"
service:
  - name: "pandalens"
    entrypoint: "pandalens_service.pandalens_service.PandaLensService.run"
    exitpoint: ""
    next:
      - "output:websocket"
output:
  - name: "websocket"
    entrypoint: "websocket_output.WebsocketOutput.send"
    exitpoint: ""
  - name: "video_output"
    entrypoint: "video_output.VideoOutput.play"
    exitpoint: "video_output.VideoOutput.stop"