# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_metrics_data.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ma_collision_data_pb2 as ma__collision__data__pb2
from . import ma_punch_data_pb2 as ma__punch__data__pb2
from . import ma_sequence_data_pb2 as ma__sequence__data__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ma_metrics_data.proto\x1a\x17ma_collision_data.proto\x1a\x13ma_punch_data.proto\x1a\x16ma_sequence_data.proto\"\x94\x01\n\x0bMetricsData\x12\x15\n\rreaction_time\x18\x01 \x01(\x02\x12\x1e\n\npunch_data\x18\x02 \x01(\x0b\x32\n.PunchData\x12$\n\rsequence_data\x18\x03 \x01(\x0b\x32\r.SequenceData\x12(\n\x0e\x63ollision_data\x18\x04 \x01(\x0b\x32\x10.MaCollisionData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_metrics_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METRICSDATA']._serialized_start=96
  _globals['_METRICSDATA']._serialized_end=244
# @@protoc_insertion_point(module_scope)
