# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_post_session_metrics.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dma_post_session_metrics.proto\"\xb2\x01\n\x14MaPostSessionMetrics\x12\x15\n\rtotal_punches\x18\x01 \x02(\x05\x12\x17\n\x0f\x63orrect_punches\x18\x02 \x02(\x05\x12\x1a\n\x12off_target_punches\x18\x03 \x02(\x05\x12\x19\n\x11\x62\x61\x64_angle_punches\x18\x04 \x02(\x05\x12\x19\n\x11\x61vg_reaction_time\x18\x06 \x02(\x02\x12\x18\n\x10session_duration\x18\x07 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_post_session_metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPOSTSESSIONMETRICS']._serialized_start=34
  _globals['_MAPOSTSESSIONMETRICS']._serialized_end=212
# @@protoc_insertion_point(module_scope)
