# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_punch_type.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ma_punch_type.proto*I\n\tPunchType\x12\x0c\n\x08LEFT_JAB\x10\x00\x12\r\n\tRIGHT_JAB\x10\x01\x12\x0e\n\nLEFT_CROSS\x10\x02\x12\x0f\n\x0bRIGHT_CROSS\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_punch_type_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUNCHTYPE']._serialized_start=23
  _globals['_PUNCHTYPE']._serialized_end=96
# @@protoc_insertion_point(module_scope)
