# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_punch_data.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ma_punch_type_pb2 as ma__punch__type__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ma_punch_data.proto\x1a\x13ma_punch_type.proto\"W\n\tPunchData\x12\x10\n\x04hand\x18\x01 \x01(\x05:\x02-1\x12(\n\npunch_type\x18\x02 \x01(\x0e\x32\n.PunchType:\x08LEFT_JAB\x12\x0e\n\x04name\x18\x03 \x01(\t:\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_punch_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUNCHDATA']._serialized_start=44
  _globals['_PUNCHDATA']._serialized_end=131
# @@protoc_insertion_point(module_scope)
