# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_session_config_data.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ma_pad_config_pb2 as ma__pad__config__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cma_session_config_data.proto\x1a\x13ma_pad_config.proto\"X\n\x11SessionConfigData\x12\x1f\n\x0bpad_configs\x18\x01 \x03(\x0b\x32\n.PadConfig\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\x12\x10\n\x08interval\x18\x03 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_session_config_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SESSIONCONFIGDATA']._serialized_start=53
  _globals['_SESSIONCONFIGDATA']._serialized_end=141
# @@protoc_insertion_point(module_scope)
