# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ma_sequence_data.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ma_punch_data_pb2 as ma__punch__data__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ma_sequence_data.proto\x1a\x13ma_punch_data.proto\"+\n\x0cSequenceData\x12\x1b\n\x07punches\x18\x01 \x03(\x0b\x32\n.PunchData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ma_sequence_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEQUENCEDATA']._serialized_start=47
  _globals['_SEQUENCEDATA']._serialized_end=90
# @@protoc_insertion_point(module_scope)
