# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaze_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgaze_data.proto\"\xbd\x02\n\x08GazeData\x12\x11\n\x07\x64\x65tails\x18\x02 \x01(\t:\x00\x12\x18\n\rhead_origin_x\x18\x03 \x01(\x01:\x01\x30\x12\x18\n\rhead_origin_y\x18\x04 \x01(\x01:\x01\x30\x12\x18\n\rhead_origin_z\x18\x05 \x01(\x01:\x01\x30\x12\x15\n\nhead_dir_x\x18\x06 \x01(\x01:\x01\x30\x12\x15\n\nhead_dir_y\x18\x07 \x01(\x01:\x01\x30\x12\x15\n\nhead_dir_z\x18\x08 \x01(\x01:\x01\x30\x12\x17\n\x0c\x65ye_origin_x\x18\t \x01(\x01:\x01\x30\x12\x17\n\x0c\x65ye_origin_y\x18\n \x01(\x01:\x01\x30\x12\x17\n\x0c\x65ye_origin_z\x18\x0b \x01(\x01:\x01\x30\x12\x14\n\teye_dir_x\x18\x0c \x01(\x01:\x01\x30\x12\x14\n\teye_dir_y\x18\r \x01(\x01:\x01\x30\x12\x14\n\teye_dir_z\x18\x0e \x01(\x01:\x01\x30')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gaze_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GAZEDATA']._serialized_start=20
  _globals['_GAZEDATA']._serialized_end=337
# @@protoc_insertion_point(module_scope)
