# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaze_point_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gaze_point_data.proto\"\x9d\x01\n\rGazePointData\x12\x13\n\x08\x63\x61mera_x\x18\x04 \x01(\x01:\x01\x30\x12\x13\n\x08\x63\x61mera_y\x18\x05 \x01(\x01:\x01\x30\x12\x13\n\x08\x63\x61mera_z\x18\x06 \x01(\x01:\x01\x30\x12\x11\n\x07\x64\x65tails\x18\x07 \x01(\t:\x00\x12\x12\n\x07world_x\x18\x08 \x01(\x01:\x01\x30\x12\x12\n\x07world_y\x18\t \x01(\x01:\x01\x30\x12\x12\n\x07world_z\x18\n \x01(\x01:\x01\x30')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gaze_point_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GAZEPOINTDATA']._serialized_start=26
  _globals['_GAZEPOINTDATA']._serialized_end=183
# @@protoc_insertion_point(module_scope)
