# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_event_sequence_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import key_event_data_pb2 as key__event__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkey_event_sequence_data.proto\x1a\x14key_event_data.proto\"9\n\x14KeyEventSequenceData\x12!\n\nkey_events\x18\x01 \x03(\x0b\x32\r.KeyEventData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_event_sequence_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_KEYEVENTSEQUENCEDATA']._serialized_start=55
  _globals['_KEYEVENTSEQUENCEDATA']._serialized_end=112
# @@protoc_insertion_point(module_scope)
