# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: direction_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64irection_data.proto\"\xb7\x01\n\rDirectionData\x12\x13\n\tdest_dist\x18\x01 \x01(\t:\x00\x12\x17\n\rdest_duration\x18\x02 \x01(\t:\x00\x12\x13\n\tcurr_dist\x18\x03 \x01(\t:\x00\x12\x17\n\rcurr_duration\x18\x04 \x01(\t:\x00\x12\x14\n\ncurr_instr\x18\x05 \x01(\t:\x00\x12\x18\n\x0e\x63urr_direction\x18\x06 \x01(\t:\x00\x12\x1a\n\x0b\x61udio_instr\x18\x07 \x01(\x08:\x05\x66\x61lse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'direction_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DIRECTIONDATA']._serialized_start=25
  _globals['_DIRECTIONDATA']._serialized_end=208
# @@protoc_insertion_point(module_scope)
