# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_wear_os_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65xercise_wear_os_data.proto\"\xd1\x02\n\x12\x45xerciseWearOsData\x12\x16\n\nstart_time\x18\x01 \x01(\x03:\x02-1\x12\x17\n\x0bupdate_time\x18\x02 \x01(\x03:\x02-1\x12\x14\n\x08\x64uration\x18\x03 \x01(\x03:\x02-1\x12\x13\n\x08\x63urr_lat\x18\x04 \x01(\x01:\x01\x30\x12\x13\n\x08\x63urr_lng\x18\x05 \x01(\x01:\x01\x30\x12\x13\n\x07\x62\x65\x61ring\x18\x06 \x01(\x05:\x02-1\x12\x14\n\x08\x64istance\x18\x07 \x01(\x01:\x02-1\x12\x14\n\x08\x63\x61lories\x18\x08 \x01(\x01:\x02-1\x12\x16\n\nheart_rate\x18\t \x01(\x01:\x02-1\x12\x1a\n\x0eheart_rate_avg\x18\n \x01(\x01:\x02-1\x12\x11\n\x05steps\x18\x0b \x01(\x05:\x02-1\x12\x11\n\x05speed\x18\x0c \x01(\x01:\x02-1\x12\x15\n\tspeed_avg\x18\r \x01(\x01:\x02-1\x12\x18\n\x0e\x63urrent_status\x18\x0e \x01(\t:\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exercise_wear_os_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXERCISEWEAROSDATA']._serialized_start=32
  _globals['_EXERCISEWEAROSDATA']._serialized_end=369
# @@protoc_insertion_point(module_scope)
