# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: random_routes_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import route_data_pb2 as route__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18random_routes_data.proto\x1a\x10route_data.proto\".\n\x10RandomRoutesData\x12\x1a\n\x06routes\x18\x01 \x03(\x0b\x32\n.RouteData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'random_routes_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RANDOMROUTESDATA']._serialized_start=46
  _globals['_RANDOMROUTESDATA']._serialized_end=92
# @@protoc_insertion_point(module_scope)
