# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10route_data.proto\"\xba\x01\n\tRouteData\x12\x10\n\x08route_id\x18\x01 \x01(\x05\x12\x17\n\x0froute_map_image\x18\x02 \x01(\x0c\x12\x13\n\tdest_dist\x18\x03 \x01(\t:\x00\x12\x17\n\rdest_duration\x18\x04 \x01(\t:\x00\x12\x14\n\ndifficulty\x18\x05 \x01(\t:\x00\x12\x0f\n\x05level\x18\x06 \x01(\t:\x00\x12\x13\n\x07toilets\x18\x07 \x01(\x05:\x02-1\x12\x18\n\x0cwater_points\x18\x08 \x01(\x05:\x02-1')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ROUTEDATA']._serialized_start=21
  _globals['_ROUTEDATA']._serialized_end=207
# @@protoc_insertion_point(module_scope)
