# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: running_live_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17running_live_data.proto\"\xb7\x01\n\x0fRunningLiveData\x12\x12\n\x08\x64istance\x18\x01 \x01(\t:\x00\x12\x14\n\nheart_rate\x18\x02 \x01(\t:\x00\x12\x0f\n\x05speed\x18\x03 \x01(\t:\x00\x12\x12\n\x08\x63\x61lories\x18\x04 \x01(\t:\x00\x12\x12\n\x08\x64uration\x18\x05 \x01(\t:\x00\x12\x0e\n\x04time\x18\x06 \x01(\t:\x00\x12\x15\n\x0binstruction\x18\x07 \x01(\t:\x00\x12\x1a\n\x0b\x61udio_instr\x18\x08 \x01(\x08:\x05\x66\x61lse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'running_live_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RUNNINGLIVEDATA']._serialized_start=28
  _globals['_RUNNINGLIVEDATA']._serialized_end=211
# @@protoc_insertion_point(module_scope)
