# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: running_target_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19running_target_data.proto\"S\n\x11RunningTargetData\x12\x11\n\x05speed\x18\x01 \x01(\t:\x02-1\x12\x14\n\x08\x64istance\x18\x02 \x01(\t:\x02-1\x12\x15\n\rtraining_mode\x18\x03 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'running_target_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RUNNINGTARGETDATA']._serialized_start=29
  _globals['_RUNNINGTARGETDATA']._serialized_end=112
# @@protoc_insertion_point(module_scope)
