# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: running_camera_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19running_camera_data.proto\"\xba\x01\n\x11RunningCameraData\x12\x15\n\ttimestamp\x18\x01 \x01(\x03:\x02-1\x12\x16\n\nposition_x\x18\x02 \x01(\x01:\x02-1\x12\x16\n\nposition_y\x18\x03 \x01(\x01:\x02-1\x12\x16\n\nposition_z\x18\x04 \x01(\x01:\x02-1\x12\x16\n\nrotation_x\x18\x05 \x01(\x01:\x02-1\x12\x16\n\nrotation_y\x18\x06 \x01(\x01:\x02-1\x12\x16\n\nrotation_z\x18\x07 \x01(\x01:\x02-1')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'running_camera_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RUNNINGCAMERADATA']._serialized_start=30
  _globals['_RUNNINGCAMERADATA']._serialized_end=216
# @@protoc_insertion_point(module_scope)
