# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waypoints_list_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import waypoint_data_pb2 as waypoint__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19waypoints_list_data.proto\x1a\x13waypoint_data.proto\"6\n\x11WaypointsListData\x12!\n\x0ewaypoints_list\x18\x01 \x03(\x0b\x32\t.Waypoint')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'waypoints_list_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WAYPOINTSLISTDATA']._serialized_start=50
  _globals['_WAYPOINTSLISTDATA']._serialized_end=104
# @@protoc_insertion_point(module_scope)
