# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard_request_live_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!dashboard_request_live_data.proto\"F\n\x18\x44\x61shboardRequestLiveData\x12\x12\n\nrequest_id\x18\x01 \x02(\x05\x12\x16\n\x0erequest_status\x18\x02 \x02(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_request_live_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DASHBOARDREQUESTLIVEDATA._serialized_start=37
  _DASHBOARDREQUESTLIVEDATA._serialized_end=107
# @@protoc_insertion_point(module_scope)
