# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard_live_running_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!dashboard_live_running_data.proto\"\xd0\x01\n\x18\x44\x61shboardLiveRunningData\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x12\n\nstart_time\x18\x02 \x02(\x03\x12\x10\n\x08\x63\x61lories\x18\x03 \x02(\x05\x12\x12\n\nheart_rate\x18\x04 \x02(\x05\x12\x10\n\x08\x64istance\x18\x05 \x02(\x02\x12\r\n\x05speed\x18\x06 \x02(\x02\x12\x11\n\tavg_speed\x18\x07 \x02(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x08 \x02(\x05\x12\x10\n\x08\x63urr_lat\x18\t \x02(\x01\x12\x10\n\x08\x63urr_lng\x18\n \x02(\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_live_running_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DASHBOARDLIVERUNNINGDATA._serialized_start=38
  _DASHBOARDLIVERUNNINGDATA._serialized_end=246
# @@protoc_insertion_point(module_scope)
